### ISSUE TITLE
Note time and duration give incorrect timing for certain MIDI files

### ISSUE THREAD

**Issue by MysteryPancake** [Tonejs/MidiConvert#116] opened 2020-07-31 15:51 UTC
[For example, this MIDI file has a BPM of 230](https://www.midiworld.com/download/4838), but the note timing information is much slower.

Perhaps the BPM is not detected correctly for certain MIDI files?

The tempo information is preserved when opening this MIDI file in external DAWs such as FL Studio.

**Comment by tambien** [comment] 2020-08-02 17:22
looks like the issue is that the tempo was not on the first track where it usually is. now it looks for tempo changes on any track so should be fixed

**Closed as completed** 2020-08-02 17:22 UTC

**Comment by MysteryPancake** [comment] 2020-08-03 06:42
Thank you so much! It is fixed now.
