### ISSUE TITLE
Feature request: support for tempo modulation

### ISSUE THREAD

**Issue by YuiyuD** [Tonejs/MidiConvert#40] opened 2017-08-07 12:11 UTC
I love your tool, but like a title, when I converting midi have multi tempo, the times not coincide anymore, can you improve it! Thank you so much for this!
![image](https://user-images.githubusercontent.com/28624505/29026034-dfb1bde4-7ba3-11e7-8c67-257baa6f6f84.png)

**Comment by sliceofcake** [comment] 2017-08-09 05:57
[Until you get a response, see #32]

**Comment by tambien** [comment] 2017-09-23 18:32
Currently only one tempo is supported

**Comment by LenweSaralonde** [comment] 2018-04-06 22:15
I need this for my project so I implemented it : https://github.com/Tonejs/MidiConvert/pull/55
The tests needs to be adjusted since one of the MIDI files has tempo variation.

**Comment by tambien** [comment] 2019-02-15 00:29
duplicate of #63

**Closed by tambien** 2019-02-15 00:29 UTC
