### ISSUE TITLE
typescript fails to compile

### ISSUE THREAD

**Issue by kn0ll** [Tonejs/MidiConvert#38] opened 2017-07-11 15:30 UTC
`Error in MidiConvert.d.sts (7,2): error TS1036: Statements are not allowed in ambient contexts`

removing semi-colons from the export declarations fixes the issue for me. using `"typescript": "^2.3.4"`.

**Comment by oli-ver** [comment] 2017-09-22 17:11
Can someone please fix this? This issue is still a problem (^0.4.1).

**Comment by kn0ll** [comment] 2017-09-23 15:37
@oli-ver 

i've fixed it in a pull request here that i'm starting to expect will never get reviewed or merged: https://github.com/Tonejs/MidiConvert/pull/39 (and verified the issue still exists up to Typescript 2.5.2)..

so, one option would be to pull this commit into your own fork and use that (that's what i was doing for a while).

another option, if possible for your project,  is actually never importing the main library at all. i removed the calls to `import * as MidiConvert from 'midiconvert'`, and instead imported methods i needed directly (like `import {midiToPitch} from 'midiconvert/src/Util'`). this seemed to prevent the TS compiler from trying to handle anything in MidiConvert.

**Comment by tambien** [comment] 2017-09-23 18:32
merged! sorry for the delay

**Closed as completed by tambien** 2017-09-23 18:32 UTC

**Comment by jsphweid** [comment] 2017-10-30 02:49
@tambien @kn0ll 

Not sure what the issue is still but when I clone this project, there are no semi-colons (yay).

When I install this package as a dependency to another project, however, src/MidiConvert.d.ts contains the semi-colons (nooo...)

What is the issue? Perhaps, despite being merged, the package version hasn't been advanced? The guy above reported this happening at 0.4.1. Then you merged. But we're still at 0.4.1.

**Comment by tambien** [comment] 2017-10-30 16:04
just published again
